name: Linkspector wiki
on: [push]
jobs:
  check-links:
    name: runner / linkspector wiki
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          fail_on_error: false
