name: Fegyver md tables to json

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: '3.13.0'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        # Install dependencies if requirements.txt exists
        # if [ -f "requirements.txt" ]; then pip install -r requirements.txt; fi

    - name: Execute Script
      run: python code/md_table_to_json.py

    - name: Check for Changes
      id: changes
      run: echo "::set-output name=changes::$(git status --porcelain)"

    - name: Configure Git
      if: steps.changes.outputs.changes != ''
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"

    - name: Commit Changes
      if: steps.changes.outputs.changes != ''
      run: |
        git add .
        git commit -m "GitHub Action: md_table_to_json.py"

    - name: Push Changes
      if: steps.changes.outputs.changes != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push
